name: List packages

on: [push, pull_request]

jobs:
  test:
    name: List packages action
    runs-on: ubuntu-latest
    steps:
      - name: List packages
        run: |
          dpkg -l
          dpkg -l *dev
          dpkg -l sql*
      
